name: Mirror Website and Commit

on:
  workflow_dispatch:

jobs:
  mirror-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0  # needed for committing

      - name: Run wget to mirror website
        run: |
          mkdir -p mirrored_site
          cd mirrored_site
          wget -m -p -E -k https://www.walkertapeco.com

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push
        run: |
          git add -A
          git commit -m "Add mirrored copy of walkertapeco.com" || echo "No changes to commit"
          git push
